name: test-dummy
on:
  workflow_dispatch:
    inputs:
      workspace_name:
        description: 'Ù‹name of the TF cloud workspace'
        required: true
        default: 'cloud_user_p_2f08bb21'
        type: string

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/vinayprakash893/azure-tf-self-service/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{ "event_type": "detail-log", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'","filename": "failure"}}'