name: self-service-call-payload-pr

on:
  repository_dispatch:
    types: [test_result]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

#need to add below permission in Setting 

jobs:
  Changing-the_stuffs:
    #if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          repository: ${{ github.event.client_payload.repository }}
        run: echo $repository
      - env:
          workspace_name: ${{ github.event.client_payload.workspace_name }}
        run: echo $workspace_name
      - env:
          resource_group_name: ${{ github.event.client_payload.resource_group_name }}
        run: echo $resource_group_name
      - env:
          storage_account_name: ${{ github.event.client_payload.storage_account_name }}
        run: echo $storage_account_name

      - uses: actions/checkout@v3



      - name: writing logs
        shell: pwsh
        run: |
          # Invoke-Pester main.tf -Passthru
          Write-Host "before changing"
          cat main.tf
          $TF_FILE_PATH ='main.tf'
          Write-Host "TF_FILE_PATH:->"
          Write-Host $TF_FILE_PATH
          $REPLACE_CONTENT = 'workspace_name_here'
          $REPLACE_WITH_CONTENT = "${{ github.event.client_payload.workspace_name }}"
          ((Get-Content -path $TF_FILE_PATH -Raw) -replace $REPLACE_CONTENT, $REPLACE_WITH_CONTENT) | Set-Content -Path $TF_FILE_PATH
          Write-Host "after changing"
          Write-Host "------------------------------------------------------------------------------"
          cat main.tf