name: workflow_01
on:
  workflow_dispatch:
    inputs:
      workflow_02:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

      workflow2_name:
        description: 'GitHub Account Owner'
        required: true
        default: 'namevalue'

      workflow2_type:
        description: 'repo-name'
        required: true
        default: 'typevalue' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/vinayprakash893/azure-terrafrom-vny-actions/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{ "event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'","worflowname2": "'${{ github.event.inputs.workflow2_name }}'" }}'
      # - uses: actions/checkout@v3