name: self_service_input
on:
  workflow_dispatch:
    inputs:
      workspace_name:
        description: 'Ù‹name of the TF cloud workspace'
        required: true
        default: 'cloud_user_p_2f08bb21'

      resource_group_name:
        description: 'Resource Group name'
        required: true
        default: '1-cdcbf205-playground-sandbox'

      storage_account_name:
        description: 'storage_account_name'
        required: true
        default: 'mystoragevnyacgtest' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/vinayprakash893/azure-terrafrom-vny-actions/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{ "event_type": "self_service", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'","workspace_name": "'${{ github.event.inputs.workspace_name }}'","resource_group_name": "'${{ github.event.inputs.resource_group_name }}'","storage_account_name": "'${{ github.event.inputs.storage_account_name }}'" }}'
      # - uses: actions/checkout@v3